---
title: "list_columns"
output: github_document
---

```{r setup,include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =0.6,
  out.width = "90%"
) 

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


## Lists 
You can put anything in a list.
```{r}
l=list(
vec_numeric=5:8,
vec_logical = c(TRUE, TRUE, TRUE, FALSE),
mat=matrix(1:8,nrow=2,ncol=4),
summary=summary(rnorm(100)))

```

```{r}
l
l$vec_numeric
l[[1]]
mean(l[["vec_numeric"]])
```


## `for` loop
create a new list.

```{r}
list_norm =
   list(
    a = rnorm(20, mean=3, sd=1),
    b = rnorm(20, mean=0, sd=5),
    c = rnorm(20, mean=10, sd=.2),
    d = rnorm(20, mean=-3, sd=1)
  )
```

```{r}
list_norm
```

pause and get my old function

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each list element

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```



Let's use a for loop:
```{r}
output=vector("list",length=4)

for (i in 1:4){
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  }
```

#lets try map
```{r}
output=map(list_norm,mean_and_sd)
```

what if you want a different function?
```{r}
output=map(list_norm,median)
```

```{r}
output=map_dbl(list_norm,median)
```

id will be in the new column called input 
```{r}
output=map_df(list_norm,mean_and_sd,.id="input")
```


## List columns!
```{r}
listcol_df=tibble(
  name = c("a","b","c","d"),
  samp=list_norm
)
```

```{r}
listcol_df %>% pull(name)
listcol_df %>% pull(samp)
listcol_df %>% 
  filter(name =="a")
```

Let's try some operation
```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
```
can i just ..map?
```{r}
map(listcol_df$samp,mean_and_sd)
```
so can i add a list column?

```{r}
listcol_df %>% 
  mutate(summary=map_df(samp,mean_and_sd),
         medians=map_dbl(samp,median))
```


